/*12) Find the total revenue generated by each employee*/

/*
	(Total Revenue) Calculates the total revenue generated by each employee by multiplying the quantity from the order_details table with the unit price from the products table.
	(GROUP BY) Ensures that the calculation is performed for each unique employee ID and name.
*/


SELECT  employees.employee_id,
CONCAT(employees.first_name, ' ', employees.last_name) AS employee_name,
SUM(order_details.quantity * products.unit_price) AS total_revenue
FROM employees
JOIN orders ON employees.employee_id = orders.employee_id
JOIN order_details ON orders.order_id = order_details.order_id
JOIN products ON order_details.product_id = products.product_id
GROUP BY employees.employee_id,   employee_name;


